---
AllCops:
  TargetRubyVersion: 2.1
Metrics/ClassLength:
  Exclude:
    - test/**/*.rb
Naming/FileName:
  Exclude:
    - lib/jekyll-netlify.rb
Metrics/MethodLength:
  Max: 30
Metrics/AbcSize:
  Max: 30
Metrics/BlockLength:
  Exclude:
    - test/**/*.rb
Style/TrailingCommaInLiteral:
  Enabled: false
Style/TrailingCommaInArguments:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Style/MultilineTernaryOperator:
  Enabled: false
Style/ConditionalAssignment:
  Enabled: false
Style/GuardClause:
  Enabled: false
